version: '3'
services:
  mfa_passport_bot:
    depends_on:
      - mongodb
    build: .
    volumes:
      - .:/mfa_passport_bot
    environment:
      - TZ=Europe/London
    networks:
      - passport_net

  mongodb:
    image: mongo:4.4
    ports:
      - '27003:27017'
    volumes:
      - dbdata1:/data/db
    restart: on-failure
    networks:
      - passport_net

volumes:
  dbdata1:

networks:
  passport_net:
    driver: bridge
